### ISSUE TITLE
Reference title not showing if on new line

### ISSUE THREAD

**Issue by AdrianHordyk** [hadley/pkgdown#178]
Rd files in package have been created manually, and `title` text starts on new line in most of the Rd files. The title does not show in the Reference page or the specific documentation page for these Rd files.

Example:
\title{My Title} 
works but,
\title{
My Title
} 
does not. 
Easy fix? Or manually change the Rd files? Roxygen not an option at the moment.

**Comment by hadley** [comment]
I think that should do it. Please let me know either way.

**Comment by AdrianHordyk** [comment]
Nope, unfortunately not. Problem still remains.  
I think it is being caused by `\n`, but not sure how to deal with it.
Thanks for looking into this.

**Comment by jranke** [comment]
I think the problem is here https://github.com/hadley/pkgdown/blob/master/R/package.r#L89-L93

The line `purrr::map_chr(c(1, 1))` assumes that the title tag returned by the parser has only one element. However, if the title starts with a newline, it has two. As an example, the Rd tag list containing the title tag list for https://github.com/jranke/mkin/blob/master/man/add_err.Rd looks like this

```
List of 1
 $ :List of 2
  ..$ :Classes 'TEXT', 'tag'  chr "\n"
  ..$ :Classes 'TEXT', 'tag'  chr "  Add normally distributed errors to simulated kinetic degradation data\n"
  ..- attr(*, "class")= chr [1:2] "tag_title" "tag"
 - attr(*, "class")= chr [1:2] "Rd" "tag"
```

As the R help system has no problem with title tags formatted like this, it would be great if they were also handled by pkgdown.

**Comment by jranke** [comment]
Ah, reading my own post I realize that the problem is that only the first item gets the `tag_title`, the second entry just has class `tag`...

**Comment by jranke** [comment]
So the problem applears to be in [`set_classes`](https://github.com/hadley/pkgdown/blob/master/R/rd.r#L27-L55). This is too complicated for me, sorry, I give up for now.

**Comment by hadley** [comment]
I think it should probably just call `as_html` instead of pulling out the first element.

**Comment by jranke** [comment]
But as `set_classes` does not set the right class for the second (or third...) item, we do not find all elements of the title.

**Comment by hadley** [comment]
I would be extremely surprised if `set_classes` was doing the wrong as the rest of the conversion of Rd to html is fine.  I think you're misreading the output from `str()`.

**Comment by jranke** [comment]
Yes, `set_classes` was not the culprit, I did misread the output from `str()`! Thanks for catching that!
