### ISSUE TITLE
Improve density of function display on reference page

### ISSUE THREAD

**Issue by jjallaire** [hadley/pkgdown#275]
I think it's useful when taking in what a package (or particular area of functionality within a package) can do to see as many functions as possible onscreen at once. It's also helpful to have a brief description of the function. I'm thinking of something like this: http://shiny.rstudio.com/reference/shiny/latest/

Currently the density of functions is low (resulting in scrolling) and lacks descriptions. It would be nice to provide an alternate layout as an option and/or the new default layout.

**Comment by hadley** [comment]
One problem with the current shiny display is that it highlights the "name" over the aliases (i.e. "updateTabsetPanel (updateNavbarPage, updateNavlistPanel)"), but that's easily resolved. I think the main challenge is extending the templating system so that there's some to place commas between the aliases, not just before/after.

Looking at the current display, I'm now not sure why I preferred it to "shiny" style. It does seem very low density.
