### ISSUE TITLE
Long section heading (h2) wrapping due to anchor

### ISSUE THREAD

**Issue by kuhnrl30** [hadley/pkgdown#308]
Long headings wrap off screen due to the margin settings.  The margin-left on .hasAnchor is set to -30px to adjust for the 30px width in a.anchor.   I saw this on a mobile view.  
![image](https://cloud.githubusercontent.com/assets/7245475/24587490/bfe4892e-1785-11e7-90db-28700128452f.png)
#192

**Comment by DavisVaughan** [comment]
I've changed the `pkgdown.css` to shift the anchor margin by -30px instead of the text itself. This seems to work great on both mobile and browser! You can see the change live [here](https://davisvaughan.github.io/tidyquant/articles/TQ00-introduction-to-tidyquant.html). Note how the long headers wrap and align correctly.

```
/* Section anchors ---------------------------------*/

.hasAnchor {
  /*margin-left: -30px;*/
}

a.anchor {
  display:inline-block;
  width: 30px;
  height: 30px;
  visibility: hidden;
  margin-left: -30px; /*Shift the anchor instead*/

  background-image: url(./link.svg);
  background-repeat: no-repeat;
  background-size: 20px 20px;
  background-position: center center;
}
```

**Comment by hadley** [comment]
Thanks! I additionally hid them on small widths since you can't see them anyway.
